---
title: "Classical Criminology"
subtitle: "SOC371, Summer 2020"
author: "Chuck Lanfear"
date: "Jun 24, 2020<br>Updated: `r gsub(' 0', ' ', format(Sys.Date(), format='%b %d, %Y'))`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ../style/xaringan-themer.css
    nature:
      highlightStyle: tomorrow-night-bright
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["center","top"]
---


# Overview

1. Historical Context

2. Theoretical Assumptions

3. Principles of Justice

4. Criticisms

---
class: inverse
# Historical Background
  
---
# 18th Century Europe

A "successful despotism", characterized by:

* Arbitrary power of aristocracy and church

--

* Laws against criticism of state and religion.

--

* Militarized police with extensive spying

--

* Torture widespread for compelling testimony or doling punishment

--

* Secret accusations and presumption of guilt

???

Interestingly presumption of innocence dates back to at least the Code of Hammurabi almost 4000 years ago

But hammurabi also codified class stratification

--

* Widespread corruption


---
# The Enlightenment

A philosophical and scientific response to the social context of continental Europe.

&zwj;Grounding: Reason and empiricism

* Emergence of social sciences--"a science of man"
* Theories of governance: natural laws as basis of order


???

For many, envisioned a return to an idealized Greece of Plato

Be wary of beautiful visions of the past written by the wealthy and powerful or those they support.

--

&zwj;Values: Liberty, progress, and religious tolerance

* People should be free to do as they wish without harming others.
* Response to religious conflict--Thirty Years' War

???

1618 to 1648; Killed > 8 million including 20% of Germany.

Defenestration of Prague when Bohemian protestants threw Holy Roman Emperor Ferdinand's reps out a window then elected a king.

--

&zwj;Goals: Reform system to protect individual rights

--

&zwj;Results: Undermined authority of monarchy and church--French revolution

* Not necessarily democratic: Plato's "philosopher king"

???

The thinkers were a new form of aristocracy, apart from feudal system

Naturally, the best people to rule the land looked a lot like them.

---
# Beccaria

*On Crimes and Punishments* (1764) was a reformist manifesto and indictment of European justice system.

--

Like virtually all influential works, composed in conversation with other thinkers and rooted in context.

* Inspired by English justice system
* Social contract from John Locke and Thomas Hobbes

--

In turn, widely influential:

* Jeremy Bentham, most directly
* US "Founding Fathers"

???

Elements can be found in US constitution

--

Like most academic work we will study, it begins with a series of strong assumptions.

Proposed policies emerge logically from these assumptions.

---
class: inverse
# Theoretical Assumptions

---
# Human Behavior (Micro)

Individuals are rationally self-interested:

--

* Free Will

   + There are no external influences on behavior
   + Therefore, people are *responsible* for their behavior

--

* Hedonism

   + People seek pleasure
   + People avoid pain

--

* Rationality

   + People evaluate the consequences of all potential actions
   + They choose the result with highest pleasure and least pain

*Individuals know what is best for them and act accordingly.*

---
# Utilitarianism (Macro)

Bentham: "it is the greatest happiness of the greatest number that is the measure of right and wrong."


--

If individuals know best how to satisfy their needs and wants...

???

What is the implication for policy?

--

... to maximize the utility of all, we should avoid restricting them.

???

What is the problem with this?

--

This breaks down if individuals maximize utility at the expense of others.


*This necessitates a deal between individuals and society*

???

What if different people derive different utility from the same (disposable) object?

Redistribution is a key element of later conceptions of utilitarianism--but people quite wary of government in this period.

Bentham and later John Stuart Mill built considerably on this logic--obvious flaws are likely to have been addressed (e.g. moral *rules*, tendencies vs certainties)

Dostoevsky's Brothers Karamazov--sacrifice a child for the happiness of all

---
# Social Contract

&zwj;Consensus: Protect individual rights and property rights

* Maximize individual utility

--

The Contract: Exchange freedom to harm for protection of own rights

* Punishment is *only* justified by social contract.
* Montesquieu: "every punishment which does not arise from absolute necessity is tyrannical"

--

No basis to restrict behavior which does not infringe on others' wellbeing.

* Beccaria: Legalize suicide; abolish death penalty
* Bentham: Legalize homosexual sex; grant women's suffrage

???

All behavior is utility maximizing--including perceived harm to self!

It gets fuzzy when insanity enters the mix--this is irrationality

Also gets fuzzy when definitions of harm are widened

J.S. Mill: We cannot accept offense or disagreement as forms of harm.

---
class: inverse
# Principles of Justice

---
# Punishment

Curtail severity

* Severe punishments reduce utility needlessly

--

Proportional severity
  
* Crimes against property punished by fines
* Imprisonment when the crime deprives others of freedom

???

Issues with this?

What about fining those who cannot pay--debtors prisons.

How do you determine what is proportional?

--

*Deterrence* not reform as goal

* Just sufficiently severe to prevent crime
* Make world a better place, not exact vengeance
  
???

Issues with this?

How do we calibrate severity?
  
--

&zwj;Goal: *Make crime the irrational choice.*

---
# Criminal Law

Terms of Social Contract

* Clear delineation of expectations
* Written in common language

???

No one should be ignorant of their social obligations

--

Minimization of Law

* "To prohibit an action unnecessarily increases rather than decreases crime." (Radnowitz 9)

???

It is unreasonable to have a criminal code which is arcane 

---
# Administration

No Ex-Post Facto Legislation

???

You cannot change a contract after it is signed

--

Minimal Discretion

* Fully described laws and punishments
* Judges only determine if a law was broken
* Punishments uniform regardless of circumstances of offender

???

Judges cannot punish for uncodified behavior

All crimes have specific punishments attached to them

No mitigating circumstances

No difference between first and repeat offenders


--

Protection of Rights

* Notice of charges
* Guaranteed counsel
* Presumption of innocence

???

Built largely off the English system

Large deviation from original presumption of guilt--an accusation was sufficient for torture.

---
# Crime Prevention

Moral education

???

Individuals should desire and prefer higher pleasures

--

Reward good behavior

???

Bolster this by rewarding seeking higher pleasures

--

Punishment is last resort

* Certainty, not severity, critical element for prevention

--

Little consideration for structural causes of crime

???

A starving person stealing bread; Bentham says we can justify the first-order evil (theft) but not the second (deprivation of bread from owner)

---
class: inverse
# Criticisms

---
# Marxist critique

Reforms achieve justice only in egalitarian society

--

Capitalist mode of production is unequal

* Bonger: Capitalism *precipitates* crime by creating unequal access to life necessities
* Capitalism *creates* selfish individualism by encouraging accumulation
* Most crime will disappear under equal distribution

--

Law is part of capitalist superstructure

* Protects and legitimizes system
* Serves the wealthy
   + White collar crime not punished
   + Poverty is criminalized
   + Working is enforced
   + Organization is legally suppressed
   
???

Consider that in the late 1800s through early 1900s strikes were put down by military or hired guns

Slavery persisted deep into the 1800s in the US--facilitated capitalist gains

--

*Should strive for equality*

---
# Feminist

Patriarchy

* Government and law controlled by men
* Has lessened in US but inequities in wages, politics, family persist

--

Law reproduces patriarchy

* Domestic violence is private affair, not treated seriously
* Common law ruled out spousal rape
* Law maintains status quo
* Equal rights amendment prohibited unequal treatment
   + ... but was never ratified
   + 25 state-level ERAs
   + Race still has stricter protections than sex

???

Only ratified by 35 of needed 38

Idaho, Kentucky, Nebraska, Tennessee and South Dakota *revoked* their ratifications

--

*Should strive for equality*

---  
# Critical Race Theory

Civil rights

* Suppressed overt discrimination
* Did not change historical legacy or social structure
* Institutional discrimination survives

???

For all talk of liberty and equality, slavery lasted 100 years longer in US

--

Law reproduces status quo

* Hard to address institutional discrimination
* Some areas of law racially biased
* Agents of law enforce racial hierarchy

???

Jim Crow appeared after slavery abolished

Many laws--such as zoning laws--are still tools for segregation and exclusion

Drug laws and stop and frisk mainly enforced on minorities

--

*Should strive for equality*
      
---
# Critical Summary

Main critical viewpoints share a logic:

1. Structural problems exist

   + Source and form of problems differs
   + e.g. capitalism; patriarchy; colonialism or white supremacy

--

2. Law protects existing structure

--

3. Equality should be goal

   + Vision of equality different under each critique

--

4. Equality can be achieved only through dismantling existing structure

---
class: inverse
# Discussion

---
# For Next Time

### Readings: 

* Kauzlarich, David, and David O. Friedrichs. 2005. "Definitions of Crime." 

* Hemmens, Craig. 2005. "Defenses to Criminal Liability: Justifications and Excuses" 

### Things to pay attention to:

1. Definitions of Crime

   * These matter for how we study it, and what criminality means.

2. Departures from Classical School

   * Context matters
   * Crime may not be result of rational process
   * External influences may exist
                    