---
output:
  github_document:
    html_preview: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(pander)
```

# SOC 371
## Criminology
### University of Washington

## Important links

* [**Lecture (Zoom)**: Monday / Wednesday 8:30-10:20](https://washington.zoom.us/j/92077343334)
* [**Section AA (Zoom)**: Wednesday 3:30-4:20](https://washington.zoom.us/j/95329696409?pwd=T1BacUl2UHlha0ZPazV4cU1PeDZYQT09)
* [**Section AB (Zoom)**: Wednesday 4:30-5:20](https://washington.zoom.us/j/99914900758?pwd=b1JJNVRncTNBcS9IdVZMcHRHSktmZz09)
* [Canvas Page](https://canvas.uw.edu/courses/1436108)
* [Syllabus](docs/syllabus.html)
* [Class Mailing List](soc371a_wi21@uw.edu)

## Course Material

```{r, echo=FALSE, message=FALSE, warning=FALSE}
course_outline <- readxl::read_excel("./ignore/course_workbook.xlsx", sheet=1) %>% filter(Ignore!=1)
course_readings <- readxl::read_excel("./ignore/course_workbook.xlsx", sheet=2) %>% filter(Ignore!=1) %>%
  select(Lecture, Citation, Reading_Link)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
course_outline %>%
  select(Week, Lecture, Date, Topic, Link, Video) %>%
  filter(!is.na(Lecture)) %>%
  left_join(course_readings, by = "Lecture") %>%
  select(-Lecture) %>%
  mutate(Readings = paste0("[", Citation,"](", Reading_Link, ")")) %>%
  group_by(Date) %>%
  mutate(reading_number = as.character(row_number())) %>%
  mutate(reading_number = ifelse(!is.na(lead(reading_number)) | !is.na(lag(reading_number)), paste0("(",reading_number,") "), "")) %>%
  mutate(Link = ifelse(is.na(Link), "", Link)) %>%
  mutate(Topic = paste0("[", Topic, "](", Link, ")")) %>%
  mutate(Video = ifelse(!is.na(Video), paste0("[(Zoom Recording)](", Video, ")"), "(No Recording Yet)")) %>%
  summarize(Topic = first(Topic), Readings = paste(paste0(reading_number, Readings), collapse = "<br><br>"), Video = first(Video)) %>%
  mutate(Readings = ifelse(str_detect(Readings, "NA"), "No assigned reading", Readings)) %>%
  mutate_at(vars(-Date), ~ ifelse(is.na(.), "", .)) %>%
  mutate(Topic = case_when(
    is.na(lag(Topic)) ~ Topic,
    lag(Topic) == Topic ~ paste0(Topic, " 2"),
    lead(Topic) == Topic ~ paste0(Topic, " 1"),
    TRUE ~ Topic
  )) %>%
  arrange(Date) %>%
  mutate(Date = format(Date, "%b %e")) %>%
  mutate(`Topic and Readings` = paste0("**",Topic,"**", "<br>", Video, "<br>", Readings)) %>%
  select(Date, `Topic and Readings`) %>%
  pander(split.tables=Inf)
```
