---
title: "Definitions of Crime and Law"
subtitle: "SOC371, Summer 2020"
author: "Chuck Lanfear"
date: "Jun 29, 2020<br>Updated: `r gsub(' 0', ' ', format(Sys.Date(), format='%b %d, %Y'))`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ../style/xaringan-themer.css
    nature:
      highlightStyle: tomorrow-night-bright
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["center","top"]
---

# Overview

1. Definitions of Crime

2. Legally Accepted Defenses

3. Definition of Criminal Law

---
class: inverse
# Definitions of Crime

---
# Legalistic
  
Crime is any **culpable** action *or inaction* prohibited by law and punishable by the state as a misdemeanor or felony.

???

Legalistic definition is by far most common definition of crime

Broader norm violating, but non-criminal, behavior is under general label of deviance

Common criticism of legal definition is using it reproduces idealogical bias

--

Components:

* Criminal (in)action:  ***actus reus***

* Intent: ***mens rea***

   + Culpability is intent *and absence of defense*

--

From English common law (Edward Coke): 

.pull-left[
> *actus non facit reum nisi mens sit rea*

]
.pull-right[
> an act does not make a person guilty unless their mind is also guilty

]

--

*The presence of both criminal intent and criminal actions is called* ***concurrence***

---
# Criminal Act

*actus reus* -- "the guilty act"

???

This merely means the court must determine beyond reasonable doubt that a criminal action occurred.

--

* Crime requires action or conduct--*statuses* or *thoughts* cannot be crimes
   + ex: being an addict (*Robinson v. California*)
   + ex: thinking of murder 

???

Sometimes fuzzy: Legal argument must be made

Possession is considered an act in the US

--

Some inactions can be criminal
   * Actor must have duty to act
   + ex: Gross negligence
   + ex: Medical care
   + ex: Command responsibility

???

Duty to act can include for parents, caregivers, medical practioners, and those under contracts.

Duty of rescue applies to parents, employers, transit services, spouses (in US); also includes notifying authorities if someone is in danger.
   + This is unusual and usually unenforced in US / English system but common in civil law systems

Can also include situations where actor creates a danger--they are obligated to address it.

Can also include failure to provide information to law enforcement, report accidents, or many elements of transactions.

Command responsibility is due to war crimes

---
# Criminal Intent

*mens rea* -- "the guilty mind"

Crime is an intentional act of law violation

   + Intent that a criminal result occurs
   + Knowledge a criminal result could occur

--

Special classes of intent:

* Constructive intent

   * Unintentional negligence leading to harm
   * Reasonable person test

???

Constructive intent is when an individual may not have intended for the outcome, but a reasonable person could forsee it as a possible result.

Reckless driving that results in a death

--

* Transferred Intent

???

If you intend to harm one person, but harm another by accident, the intent transfers

--

* Exception: Strict liability

???

Strict liability only for most minor things in US: Parking tickets, drunk driving

Also statutory rape in 22 states--applies even if defendant was misled

Sometimes court entertains a "good faith" defense if defendant made active attempt to verify

---
# Legally accepted defenses:
     
* Self defense, defense of others

???

Limited to proportional response to present, unlawful, and unprovoked attack

Usually duty to retreat, can only sometimes defend property

WA has true man doctrine; "true man" is one without fauly

--

* Consent

???

Gets fuzzy--cannot consent to guarantee severe harm in many cases (or death)

--

* Duress and Necessity

???

Crime committed to prevent more serious harm including imminent harm to self

Duress supercedes consent: Your consent doesn't count under duress

Necessity is not duress because it is voluntary

--

* Entrapment
   + By estoppel
   
???

Law enforcement concocts a crime and persuades or tricks someone to commit it who otherwise would not have

Subjective and objective tests in US: Absence of predisposition of subject vs. government actions would cause normal person to violate law.

US has sometimes engaged in very predatory operations to set people up, e.g. Jacobson v. United States

By estoppel prevents court from saying defendant is protected from prosecution, then charging them later

--

* Double Jeopardy

???

Culpability not relevant here--they've already either been acquitted or convicted.

New evidence or confessions after acquittal can sometimes override this--but not everywhere
In US: Bribery of judge (no jeopardy) or second jurisdiction--military, federal, etc.

--

* Insanity

???

Insanity regard impairment of mens rea

In some ways analagous to handling of minors; can think of commitment as a similar parallel justice system
      
---
# Insanity

**M'Naghten Rule** (1843): Not culpable due to disease of mind
  
   1. Did not know nature and quality of act, and/or 
  
   2. Did not know act was wrong

???

This is oldest standard. Very subjective--difficult for courts.

--
   
**Durham Rule** (1954): Not culpable if act product of mental disease or defect
  
   * Psychiatric definition of mental disease
  
   * Burden on prosecution to demonstrate sanity.
   
???

Again, difficult for courts--having to prove sanity is difficult.

--

**Insanity Defense Act of 1984**: Not culpable if... 

> as result of a severe mental disease of defect, was unable to appreciate the nature and quality or the wrongfulness of his acts.

   * Defendant must prove insanity by "clear and convincing evidence"

???

This shifted burden of proof to the defense

---
## Alternate Definitions of Crime

Humanistic

* Identifiable Harm
   + Critique: Harm is subjective 
   + ex: Harcourt's *Illusion of Order*; J.S. Mill

???

Humanistic is based on identifiable harm

This raises different issues of subjectivity--what is harm?

Claims of harm often used to justify establishing new crimes

Counterpoint here is that if you define these as crimes they no longer reflect acts which have formal consequences--why not just call them harms?

--

Constructionist

* Crime is a status not a behavior

???

Crime is a label we place on behaviors

Can be about studying the placing of labels--categorization; labeling theory has a lot to say about this

--

Moralistic

--

Political

???

This calls back to arbitrary power in continental Europe; need not even put a law on the books to make something criminal in many places

---
class: inverse
# Criminal Law


---
# Definition of Criminal Law
  
Specificity: "Whosoever engages in X shall be punished with Y."

Ideal characteristics:

* Politicality: Outlawed by a political authority

???

Non-political authorities cannot establish crimes

Violation of contracts is generally non-criminal

--

* Uniformity: Apply uniformly to all

???

A law which specifically excludes one category of people still applies uniformly: The exclusion is uniformly applied.

--

* Penal Sanction: Punishable by the state.

???

By definition crimes carry punishments--but there is no obligation to apply the punishment (discretion)

---
# Levels of Law

* State vs. Federal Law vs. Local

???

These are overlapping; one is subject to all at once

If an act is illegal in both state and federal, you can be prosecuted separately in both

Most people live under many overlapping codes: US, state, county, district, city.

--

* Civil vs. Criminal

???

Focus on contracts, civil wrongs, and property other than theft or destruction

Civil has lower burden of proof; beyond reasonable doubt vs. clear and convincing evidence

Do not confuse with the civil law system that is the European-origin counterpart to English common law

--

* Statutory vs. Common Law

???

Statutory is produced via legislation

Common law is produced via judicial rulings.


---
class: inverse
# Origins of Law

---
# Law as Consensus

* Law emerges from customary, consensual morality

* Origin in informal rules of interaction

* Law is just a codification 


---
# Law as Conflict

* There are many competing moralities--but only one system of law

???

Whose morality rises to the top is what matters and has consequences

--

* Stratification: 
   
   + Necessitates regulation of interaction
   
   + Induces the dominant to preserve position

???

Chambliss and Seidman's point: Complex societies need laws to regulate interaction of highly diverse groups.

But that complexity produces heterogeneity in power

Those in power preserve their position via law

This can be seen to be related to the core Durkeheimian concern with the shift between mechanical and organic solidarity.

--

* Connection to morality is tenuous

   + The immorality of the poor is criminal
   
   + Marxist Position: Moral capitalism
   
???

Immorality of the rich is ignored, tolerated, or even celebrated

Codified morality is capitalist, supports ruling class and underlies legal system to maintain capitalism

Some conceptions of subcultural deviance represent rejections of the morality enshrined in law--and substitution with others, which results in non-reliance on  law enforcement

--

* Law used to change morality

???

Law has continuously been used to attempt to change morality of target populations

Most criminologists are incredibly skeptical of this--rarely works and has serious consequences

Absent laws, norms often solve problems in groups--much larger lit out there on norms, sanctions, and collective action.

---    
# Summary

* According to legalistic definition, crime is behavior in violation of criminal law

   + Individuals must be culpable

* Criminal Law: Specific acts outlawed and punishable by the state.

   + The source of laws is debatable

   + Consensus and conflict perspectives 

---
class: inverse
# Discussion

---
# Some Questions

Kauzlarich & Friedrichs reading: These authors describe the political definition of crime as occurring almost exclusively in totalitarian or authoritarian regimes targeting political opponents and "enemies of the state". Could you argue the US has created political crimes as well? Have they been couched in more vague and politically-correct terms, or have they not happened at all?

--

Considering whether or not Law is a product of consensus versus a product of conflict, which ideal do you believe more heavily influences the current state of legislation in America?

--

Hemmes reading: What are the merits to the "retreat doctrine" versus the "true man doctrine" versus the "castle doctrine"? Should each of these always, sometimes, or never apply?

---
# Some Clarifications

* "How do the legal systems that identify behaviors like homosexuality as mental illness reconcile this as a vast majority of the time they also have strict laws listing it as a crime?"

???

Laws need not be logically compatible. People can put whatever they want on the books to accomplish a goal. Labeling it mental illness might enable commitment. May also make it mental illness but not allow it to reduce culpability.

--

"According to the passage, there are many ways to define crime, but how does one's interpretation of crime affect his/her behavior? "

???

This is one of the reasons for the humanistic side--trying to get people to think of things like deprivation as criminal, and abhorrent, so we intervene.

--

"In the article, a quote states "Today an agent of the state, such as police officer or soldier, is permitted to use reasonable force in the lawful execution of his or her duties". To what degree is considered as "reasonable force" under a normal circumstance?" and "...how is it that civilians cannot protect themselves unless they are being attacked and are not able to flee, but officers of the law may kill someone if they believe them to be of harm to themselves or others?"

???

Police aren't civilians, that's why!

Police typically don't suffer from harsh judgments over use of force. But departments have internal policies in most cases.

Police are charged with the legal capability to dole out lethal force and to do so in a broad range of situations cirvilians cannot.

--

"Can you further explain why “intent” should not be confused with “premeditation”?"

???

Premeditation means one plans to do the act prior to doing it. Intent just means the action was done voluntarily and purposefully--but they could have decided to do it right then and there.

---
# For Next Time

### Readings: 

* Baumer, Eric P. and Kevin T. Wolff. 2014. “Evaluating Contemporary Crime Drop(s) in America, New York City, and Many Other Places.” Justice Quarterly 31(1):5-38

* Western, Bruce, and Becky Pettit. 2002. “Beyond Crime and Punishment: Prisons and Inequality.” Contexts 1:37-43.

### Things to pay attention to:

1. Trends at different levels versus deviation from trends
2. Lack of certainty about causes of changing crime trends
   * Compare to certainty politicians and media attach to policies
3. Disparate impacts of incarceration
   * Contrast impacts on inequality with impacts on crime
        