---
title: "The Urban Underclass, Social Capital, and Collective Efficacy"
subtitle: "SOC371, Summer 2020"
author: "Chuck Lanfear"
date: "Jul 29, 2020<br>Updated: `r gsub(' 0', ' ', format(Sys.Date(), format='%b %d, %Y'))`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ../style/xaringan-themer.css
    nature:
      highlightStyle: tomorrow-night-bright
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["center","top"]
---

# Overview

---
# Broken Windows (Wilson & Kelling)

* Minor forms of physical and social disorder (incivilities) correlate with more serious crime
   * Graffiti, broken windows, dilapidated buildings, panhandlers, homeless
   * Broken windows signals to criminals indifference to crime
   * Low probability of being seen, reported, arrested

* Disorder also undermines community controls
   * In a few years or months, stable neioghborhoods of families who care about theri homes, children, and safety may become an inhopsital and frightening jungle.
   * Mechanisms: Changed behavior of residents; residential mobility

* Policy: Zero tolerance policing

---
# Disorder, Collective Efficacy, and Crime

[IMAGE: CE -> Disorder -> Crime]

* Broken windows hypothesis: Direct effect of disorder on crime
* Colelctive efficacy (social capital) hypothesis
   * Association between disorder and crime is spurious
   * Collective efficacy reduces disorder and crime in the neighborhood
   * Some support from Sampson & Raudenbush (1999)

---
# Field Experiments (Keizer et al. 2008 *Science*)

* Begin with broken windows hypothesis

* Mechanism: Norm violation weakens goal to act appropriately

* Descriptive norm violation (graffiti) inhibits injunctive norms (theft, littering)

* Conducted six experiments to examine cross-norm effects

* Note: Examining norm violations, not serious crimes

---
# Graffiti (Fireworks) and Littering

[TWO TABLES]

---
# Graffiti on (Litter around) Mailbox Theft of Envelope with 5 Euro Note

[Two tables]

Note: Mailing envelope and doing nothing both counted as theft.

---
# Broken Windows Experiments Across Seattle Neighborhoods

[IMAGE: Diagram from earlier, highlighting experiments]

* Embed experiments in selected Seattle neighborhoods

* Run experiments in disparate neighborhoods

* Replication of Keizer et al. and extension

---
# Mailbox Experiment: Protocol

[Table: DV counts, treatment, context: neighb CE]
[IMAGE: International District treatment]

---
# Preliminary Results: Mailbox Experiment

* Much lower theft rate in Seattle vs. Groningen
   * Despite property crime being higher in Seattle
   * Many more people walk by and do nothing
* Disorder does not increase theft
* Disorder reduces mailing
* theft is lower in high collective efficacy neighborhoods

???

ROSS NOTES:

Treatment reduces prob of mailing, no effect on stealing, increases no action.
- If we remove no action and run a logistic regression, treatment appears to increase thefts
because of this.
As expected, men more likely to steal.
Unsure of non-white effect, probably due to tract effects.
People in groups much less likely to act, possibly due to distraction. Noteworthy that people
in groups are counted individually rather than as a mass, so a group of 5 missing the letter is
big.
CE impacts stealing and no action
Busier areas have lower action counts; bystander effect or distraction (cognitive overload)

---
# Lost Letter Experiment

[IMAGE: CE <-> Prosocial behavior]

* More recent behavioral measure of CE

* REplication of Milgram et al. (1965)

* Sampson (2012): 3,303 letters dropped across 343 Chicago NCs

* Seattle letter drop
   * 24 letters each in 122 census tracts
   * Total of 2,928 letters dropped

---
# Lost Letter Experiment

[TABLE: Comparison from ASC presentation]

---
# Lost Letters Returned by Tract

[IMAGE: My heatmap by letter]

---
# Conclusion about Broken Windows

* There may be a smal effect of neighborhood disorder on crime

* CE plays an important role in cleaning up disorder

* Probably does not justify zero tolerance policing as panacea

* Unanticipated negative consequences
   * Police dislike focusing on incivilities
   * Potential for racial profiling
   * Undermines citizen-police relations

* Building CE may be more efficient

???

ROSS NOTES: 
Treatment reduces prob of mailing, no effect on stealing, increases no action.
- If we remove no action and run a logistic regression, treatment appears to increase thefts
because of this.
As expected, men more likely to steal.
Unsure of non-white effect, probably due to tract effects.
People in groups much less likely to act, possibly due to distraction. Noteworthy that people
in groups are counted individually rather than as a mass, so a group of 5 missing the letter is
big.
CE impacts stealing and no action
Busier areas have lower action counts; bystander effect or distraction (cognitive overload)



---
class: inverse
# Discussion

---
# Some Questions

---
# Some Clarifications

---
# For Next Time
