---
title: "Introduction to Criminology"
subtitle: "SOC371, Summer 2020"
author: "Chuck Lanfear"
date: "Jul 15, 2020<br>Updated: `r gsub(' 0', ' ', format(Sys.Date(), format='%b %d, %Y'))`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ../style/xaringan-themer.css
    nature:
      highlightStyle: tomorrow-night-bright
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["center","top"]
---

# Overview

1. Incapacitation vs. Selective Incapacitation

2. Criminal Careers Research

   * Delinquency in a Birth Cohort
   * Participation vs. Frequency
   * Substantive Implications
   
3. Predicting High Rate Offenders

   * RAND Studies
   * Problems of Actuarial Prediction
   

---
class: inverse
# Incapacitation vs. Selective Incapacitation

---
# Incapacitation

Segregate criminals via imprisonment to prevent future crime

* Incapacitation vs. deterrence
* Modest effects
* Expensive

---
# Selective Incapacitation

Selectively imprison high rate offenders

* How effective would this be?

* Problem is prediction

---
class: inverse
# Criminal Careers Research

---
# Delinquency in a Birth Cohort

* Philadelphia 1945 cohort (Wolfgang, Figlio, & Sellin)
   * 9,945 boys
   * 35% with police record by 18
   * Chronic offenders: 6% of cohort commit 50% of crimes
   
* Philadelphia 1958 cohort
  * 28,000
  * 7.5% of cohort: > 5 arrests, 61% of crimes
  
* Racine, WI (Shannon)
  * 25% account for 80% of arrests
  
Selective Incapacitation: Lock up this ~6%, cut crime in half

---
# Blumstein & Cohen

* Decompose crime rate into participation rate and frequency rate
   * Participation rate: Proportion of pop arrested
   * Frequency rate: Average arrests per arrested
   
$\text{Crime Rate} = \text{Participation Rate} * \text{Frequency Rate}$

$\frac{\text{# of Arrests}}{100,000} = \frac{\text{Arrested People}}{100,000} * \frac{\text{# of Arrests}}{Arrested People}$

* Implications
   + If participation high, frequency low, selective incapacitation won't work well
   + If participation is low, frequency high, selective incapacitation has great potential

---
# Empirical  Composition

* Participation Rates
   + 50-60% of urban males arrested in lifetime
   + 25% for index crimes (14% white, 50% black)
   + Recidivism: 85-95%
   
* Frequency Rates (Arrests in DC & Detroit)
   + Aggravated Assault: 2-3 per year
   + Robbery: 3-5 per year
   + Property Offenses: >5 per year
   + Auto Theft: 3 in DC; 9 in Detroit

---
# Self-Report Frequency

* Inmate reports before incarceration (RAND)
   + Robbery
      * 50% of robbers <4 per year
      * 10% of robber >70 per year
   + Burglary
      * 50% of burglars <5 per year
      * 10% of burglars >195 per year
      
* Career lengths are short
   + Average less than 6 years for serious offenses

---
# Age-Crime Curve

IMAGE

---
# Moffit and Age-Crime Curve

IMAGE

Chronic vs. Adolescent Limited

---
# Life-Course Persistent Offenders

* Serious underlying problems
   + Cognitive deficits
   + Attention Deficit Hyperactivity Disorder
   + Psychopathy

* Early maturation, large physical size

* Cumulative disadvantage

* Temper tantrums in late adulthood
   + Poor and unstable jobs
   + Poor and unstable marriages

---
# Adolescence-Limited OFfenders

* "Normal" adolescents

* Learn deviance from peers (partying, fighting, vandalism, theft)

* Learn from life-course persistents

* Age out due to life course transitions

---
# Gottfredson & Hirschi

* Ignore this research
   + Reflects unmeaningful statistical variation
   + Cannot identify career criminal before fact
   + Identify career criminal by 5+ offenses, but by then cease to be career criminal due to age
   
* Analogy: For heart attacks, prevention is better

* Question: Can we predict the chronic offender?

---
# Predicting the High Rate Offender (Greenwood)

* Interviews of California inmates using self-rports of robberies and burglaries (RAND)

* 7-point prediction scale
   + Incarceration >2 year period
   + Prior conviction for robbery and burglary
   + Juvenile conviction before age 16
   + Commitment to juvenile institution
   + Heroin or barbiturate use as a juvenile
   + Heroin or barbiturate use within 2 years of arrest
   + Employed less than half time within 2 years of arrest

---
# Sentencing Rule and Simulations (Greenwood)

* Sentencing rule: High rate offender gets 8 years in prison, all others 1 year

   + Result: Reduce robbery by 15%, imprisoned robbers by 5%
   + False positive rate of 60%, problem of false negatives
   
* RAND study
   
   + After 24 months, prediction scale does 5-10% better than chance; not significant
   
---
# Potential Problems

* Changes sentencing from doing justice to crime control

* Used unemployment as predictor--victim blaming

* Assumes individual will behave like average member of classification group (high rate offender)

* Ignores agency and reform

---
class:inverse
# Discussion

---
# Some Questions

---
# Some Clarifications

---
# For Next Time

* Hirschi, Travis. [1969] 2001. *Causes of Delinquency.* New Brunswick, N.J: Transaction Publishers. Chapter 2

* Sampson, Robert J., and John H. Laub. 1990. "Crime and Deviance over the Life Course: The Salience of Adult Social Bonds." *American Sociological Review* 55:609-27.

Things to pay attention to:

