---
title: "Introduction to Criminology"
subtitle: "SOC371, Summer 2020"
author: "Chuck Lanfear"
date: "Jun 22, 2020<br>Updated: `r gsub(' 0', ' ', format(Sys.Date(), format='%b %d, %Y'))`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ../style/xaringan-themer.css
    nature:
      highlightStyle: tomorrow-night-bright
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["center","top"]
---

# OVerview

---
# Differential Social Organization

* Static view: Organization in favor of crime vs. organization against crime

* Dynamic view: Collective action (joint behavior among two or more interdependent individuals)
   * Consensus over objective (for crime or against crime)
   * Consensus over means of attaining objective

* Result: Collective action in favor of crime vs. collective action against crime

---
# Collective Action

* Grievance requiring a collective response
* Social Structure (Resource Mobilization Theory)
   * Social network ties
   * Pre-existing organization
   * Political opportunities
   
* Collective Action Frames
   * Frame a grievance as calling for certain collective acts
   * Meanings and understandings of issues
   * Define a situation as calling for action
   * Fight over whose meaning of issues prevails--e.g. abortion, gay marriage, torture

---
# COllective Action Frames

* Frame Alignment
   * Link individual interpretations to social movement organizations' interpretations
   * Use argumentative tactics to align frames

* Effectiveness of frames
  * PRoblem and solution is defined collectively (not individually)
  * Defines antagonists as "us" versus "them"
  * Defines an injustice that can be corrected collectively

* Example: Civil Rights

[LINKL MLK I have a dream]

---
# Social Network Ties

* NEtwork Closure
   * Increases ability of individuals to influence others
   * Open Structure: C can influence A and B individually
   * Closed structure: C and A can influence B

[Image: Open and closed structures]

---
# Social Network Ties

* Strong versus weak ties
   * Strong ties to similar others provide similar information
   * Weak ties to dissimilar others provides different information
   * Example: Hearing about a job

[Image: Strong and weak ties]

---
# Social Efficacy vs. Collective Efficacy

* Collective Efficacy: A Neighborhood's capacity to resolve local problems collectively
   * Activation of capacity
   * Apply this to groups
   * Increased with strong social ties (network closure)

* Social efficacy: An individual's ability to create consensus over group objectives and procedures and translate procedures into action
   * Some individual are better able to create consensus and persuade others into collective action
   * Charismatic individuals (MLK)

---
# Social Efficacy in Different Network Positions

[IMAGE: Network diagram of positions]

Central actor is socially efficacious resident: great structural position
Two others socially efficacious but weak structural positions

---
class: inverse
# Genocide

---
# Definition of Genocide

Genocide is any of the following five acts committed with intent to destroy, in whole or in part, a national ethnic, racial, or religious group:

* Killing group members
* Causing serious bodily or mental harm to group members
* Deliberately inflicting conditions of life calculated to destroy the group as a whole or in part
* Imposing measures intended to prevent births
* Forcible transferring children of the group to another group

---
# Genocide in Darfur

* Competition between settled black tribes and nomadic arabs
   * Land, cattle, horses, and other resources
   * Desertification intensified conflict
   * Janjaweed (supported by Sudan government) vs. black African insurgents

* Arming of Arab Janjaweed militias by government in 2003
* Bombing of African villages by Sudanese government
* Government forces join Janjaweed militias in ground attacks
* Sexual violence and other atrocities
* Confiscation of property (animals, grain, seed, equipment)
* Displacement of black Africans into internal displacement camps
* Resettlement of black African regions by Arabs

---
# Differential Social Organization of Genocide

* Organization against genocide
   * Typically the state (government)
   * Black Afircan rebels and insurgents
   * The international community & the international criminal court

* Organization in Favor of Genocide
   * Arab Janjaweed anti-insurgent groups
   * Sudanese government
   * Arab settlers

* Collective action

---
# Collective Action in Favor of Genocide

* Social networks and access to resources
   * Arab Janjaweed & Sudan government forces
   * Arms and cooperation

* political opportunity: insurgent attacks

* Collective action frames
   * Define the conflict as a collective problem, not an individual grievance
   * Define opposition (black Africans) as "them" versus "us" (racism)
   * Frame injustices committed by "them" as correctable by organized actions against "them" (ethnic cleansing)

* Social Efficacy
   * Key leaders of Arab militia representing distinct areas
   * Hilal, Dawai, Shineibat, Kushayb
   * Each with strong regional social ties & social efficacy

---
# Collective Action in Favor of Genocide

* Racism frame: Emotional spark
   * "Us" vs. "Them" in zero-sum game
      * Initially over land, water, and resources
      * Gets transformed into race
  * Demonize and dehumanize African blacks

* Racial epithets
   * Individual racist expressions are transformed into collective racism
   * "Fanatical fury": Collective racist emotion unleashed on dehumanized African blacks
   * Racism: A collective instrument of organized terror
   * Reveal a reacist motive and intent (genocide)

---
# The Case for Genocide

* Racial epithets heard during attacks (reflect racial intent)
   * More likely when Sudanese government troops joined with Janjaweed militants
   * "We will eliminate all you blacks"
   * "You will have an Arab baby."

* Nearby Arab settlements often ignored in attacks

* Bombing and racial epithets combined for greater victimization

* State-sponsored murder and rape

---
# Proposed Solution: International LAw

* Call on the United Nations to define this as genocide
* Call on International Criminal Court
   * Define this as genocide
   * Indict Hillal and others for genocide (Sudan's present, Omar al Bashir was "recently" indicted)
   * End the atrocities by international intervention

---
# A Competing View

* Viewed in historical context, this is a political-economic conflict
   * Decades of conflict over land, water, animals, and other resources.
   * Arab and black identities in Darfur have been fluid for centuries 
   * British colonial rule: Re-tribalization, in which tribes would be designated new homelands
* ICC is arbitrarily taking one side over the other
   * Demonizing arabs (good vs. evil)
   * Historically atrocities have been comitted by botyh sides
* Africanists distrust the ICC
   * Not accountable to anyone
   * Except UN security council, which is dominated by US
   * External intervention will only destabilize the region
* Better solution: Internal political solution through negotation
   
   
---
class: inverse
# Discussion

---
# Some Questions

---
# Some Clarifications

---
