---
title: "Rational Choice and Deterrence"
subtitle: "SOC371, Summer 2020"
author: "Chuck Lanfear"
date: "Jun 22, 2020<br>Updated: `r gsub(' 0', ' ', format(Sys.Date(), format='%b %d, %Y'))`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ../style/xaringan-themer.css
    nature:
      highlightStyle: tomorrow-night-bright
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["center","top"]
---

L5: Deterrence
  Objectives
    Understand relationship between rational choice and deterrence
    Distinguish general versus specific deterrence
    Distinguish marginal vs absolute deterrence
    Know the variables in deterrent effects
    Understand routine activities and hotspots policing
    Understand the design and results of the Minneapolis experiment
    Understand the design and results of survey studies of general deterrence
  Deterrence doctrine
    Rational actor assumption
      In aggregate, individuals act rationally
      At margin, individuals act rationally
      Individuals respond to incentives
    General vs. specific deterrence
    Marginal vs. absolute deterrence
    Variables in deterrent effect
      Certainty, severity, celerity
  Routine Activities Theory (Rational Choice)
    Crime results from opportunities
      Motivated offenders, suitable targets, capable guardians
    Hot Spots Policing (Police as Guardians)
      Identify high crime areas, send police there
      Reduces crime but questions of displacement
  Specific deterrence
    Does punishment deter punished people?
    Studying it:
      Compare incarcerated then released vs. probationers
      But those sent to prison may be more crime prone
      Experimental design: equivalent treatment and control groups
  Minneapolis Domestic Assault Experiment (Sherman & Berk ASR 1984)
    Randomized experiment (officer pad color)
      Separate, advise, or arrest
    Criteria:
      Misdemeanor assaults, victim and offender present, probable cause of assault
    Follow up offenders (re-arrest and self report)
    Compare arrested with non-arrested
    Specific deterrence vs. labeling
    Problem: Departures from randomization
    Results:
      Small but significant deterrence effect over 24 month follow up
      Arrest had specific deterrent effect
      Caveats:
        Problem with randomization, need for replication
      New legislation ignored caveats: mandtory arrest
      NIJ funded replications
        Omaha, Milwaukee, Dade County, Colorado Springs
        Randomization by dispatcher
        No consistent deterrence, slight labeling in some studies
          Conditional: Arrest deterred married and employed; arrest increased for single and unemployed.
          More to lose if married and working
  "Deterring Delinquents" Matsueda, Kreager, Huizinga (2006) ASR
    Crime = Pr * Value (Reward) > Pr * Value (Costs)
    DYS
    Rational choice hypothesis: Perceived cost/benefit impacts future crime
    How are perceived risks formed? Rooted in reality?
    Deterrence: Perceptions should be rooted in reality
    Experiential Learning
      Baseline estimate of perceived risk (overstimate--Tittle's (1980) Shell of Illusion)
      New information used to update
    Information of Perceived Risk
      Experienced certainty: arrest/crime for each person
      Unsanctioned offenses: number of crimes for non-arrested
      Crimes of peers
    Graphical model: Formation of perceived arrest risk
    Perceived risk by experienced certainty
    Rat Choice and deterrence
      Rewards: Excitement, seen as cool
      Cost: Arrest
      Certainty: Chance of getting X for theft (violence)?
      Severity: How good or bad is this?
    Graphical mode: Perceived risk of arrest on crime
    Conclusion:
      Small deterrent effect: 10% risk equals 3% theft and 5% violence reduction
      10% seen as cool reduces theft by 6, violence by 7
      Already have high arrest and imprisonment rate--bad idea to boost it
      Some level of arrest and incarceration probably essential
      Deterrence not a panacea for crime problem.
      
---
# For Next Time