---
title: "Rational Choice and Deterrence"
subtitle: "SOC371, Summer 2020"
author: "Chuck Lanfear"
date: "Jun 22, 2020<br>Updated: `r gsub(' 0', ' ', format(Sys.Date(), format='%b %d, %Y'))`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ../style/xaringan-themer.css
    nature:
      highlightStyle: tomorrow-night-bright
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["center","top"]
---

# Overview

---

Objectives
    Understand relationship between rational choice and deterrence
    Distinguish general versus specific deterrence
    Distinguish marginal vs absolute deterrence
    Know the variables in deterrent effects
    Understand routine activities and hotspots policing
    Understand the design and results of the Minneapolis experiment
    Understand the design and results of survey studies of general deterrence

---
# Context

Criticism of the classical school lead to rejection of rational actor

Crim dominated by structural explanations

Crime as irrational behavior resulting from socialization

Since this behavior is irrational, it is a "hard test" for a theory of rational actors

Rational choice reintroduced this concept but in more realistic terms

---
# 1970's and 1980's

* Attacks on rehabilitation

* James Q. Wilson's *Thinking About Crime*: Must respond harshly to crime so those on fence won't get idea that crime pays.

---
#

Rather than focus on the intervening work first, we begin at deterrence

Deterrence is framed now in terms of rational choice but has long been basis from criminal legal policy

---
#  Deterrence Doctrine

Deterrence is simply idea that punishment can impact crime.

Modern deterrance and rational choice makes weaker assumptions than classical school


Rational actor assumption

* In **aggregate**, individuals act rationally
* At **margin**, individuals act rationally
* Individuals respond to incentives

---
# Marginal vs. absolute deterrence

* Absolute Deterrence
   + Complete prevention of the crime(s)

* Marginal Deterrence
   + Reduction in frequency of crime


---
# Variables in deterrent effect

* Certainty

   + Probability of being sanctioned
   + Objective Measures:
       * Arrest or clearance rate
       * Proportion of offenders prosecuted
   + Subjective Measures: Perceived punishment probability
   + Tittle's "Shell of Illusion"

???

Tittle's Shell of Illusion: Those never committing a crime--and thus never getting away with it--overestimate sanction risk.

This is related to the illusion most people have that certain types of law violation are incredibly rare; since at least Rome philosophers have stated that if people knew how often laws were broken, they too would break them.

--

* Severity

   + Severity of the sanction
   + This is the *cost*
   + Objective Measures: Sentence length; fine amount
   + Objective Measures: Perceived suffering

--

* Celerity (Swiftness)

   + Length of time between crime and sanction
   + Acknowledges economic time discounting
   + Less frequently used

---
class: inverse
# General vs. specific deterrence

---
# General Deterrence

Does threat of punishment deter people?

   + Perceived threat of sanctions deters individuals from crime
   + Based on perception, not personal experience
   + Punish so that others see they too will be punished
   + About reducing *crime in general*
   
Approaches

   + Changes in crime rates before/after policy changes
   + Effects of perceived risk and severity

---
# Specific Deterrence

Does punishment deter punished people?

   + Experience of punishment deters individuals from future crime
   + Based on experience, occurs only after punishment
   + About reducing *recidivism*

Approaches

   + Compare incarcerated then released vs. probationers
       + But those sent to prison may be more crime prone
       + Experimental design: Need equivalent treatment and control groups
   + Randomly vary punishment
   + Look at marginal cases--natural experiments
      





---
# Rational Choice Model

Deterrence focuses on the sanctioning.

Full rational choice models recognize variation in gains.

Material and psychic gains

Economist Gary Becker introduced rational model of crime in 1968's "Crime and Punishment: An Economic Approach"; had little impact in sociology or criminology.

Actually preceded by Short & Strodtbeck (1964), which was a more sophisticated subjective utility model anyway

Rational choice is a *general* theory of behavior--not limited to crime.

---
#

Don't estimate exact values, but rather take advantage of basic properties

All else equal, reducing reward / increasing cost reduces probability.

---
# Matsueda, Kreager, Huizinga (2006)



  "Deterring Delinquents: A rational choice model of theft and violence"  ASR
    Crime = Pr * Value (Reward) > Pr * Value (Costs)
    DYS
    Rational choice hypothesis: Perceived cost/benefit impacts future crime
    How are perceived risks formed? Rooted in reality?
    Deterrence: Perceptions should be rooted in reality
    Experiential Learning
      Baseline estimate of perceived risk (overstimate--Tittle's (1980) Shell of Illusion)
      New information used to update
    Information of Perceived Risk
      Experienced certainty: arrest/crime for each person
      Unsanctioned offenses: number of crimes for non-arrested
      Crimes of peers
    Graphical model: Formation of perceived arrest risk
    Perceived risk by experienced certainty
    Rat Choice and deterrence
      Rewards: Excitement, seen as cool
      Cost: Arrest
      Certainty: Chance of getting X for theft (violence)?
      Severity: How good or bad is this?
    Graphical mode: Perceived risk of arrest on crime
    Conclusion:
      Small deterrent effect: 10% risk equals 3% theft and 5% violence reduction
      10% seen as cool reduces theft by 6, violence by 7
      Already have high arrest and imprisonment rate--bad idea to boost it
      Some level of arrest and incarceration probably essential
      Deterrence not a panacea for crime problem.
      
      




      
---
# For Next Time

* Marshall, Chris E. 2002. “Deterrence Theory.” Pp. 512-515 in *Encyclopedia of Crime and Punishment*. Edited by D. Levinson. Beverly Hills: Sage

* Levitt, Steven D. 2002. “Deterrence.” Pp. 435-450 in *Crime: Public Policies for Crime Control*. Edited by J.Q. Wilson and J. Petersilia. Oakland, CA: ICS press



### Things to pay attention to:


* Connection to classical school

* Theoretical assumptions

* Policy implications of deterrence
